/**
 * Generates `worker.js`: the whole server in a single file.
 *
 *   node tools/build.mjs
 */
import { execFileSync } from "node:child_process";
import { readdir, readFile, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

/* Order matters, and it is not alphabetical: flattened into one file, every
   definition has to come before the ones that use it. `core.mjs` is what the
   platforms borrow, and `dispatch.mjs` is what calls them, so it goes last.
   The platforms between them can be in any order because none of them uses
   another —that is the point of having one file per site— and they are sorted
   anyway so that two builds of the same sources produce the same bytes.

   Each entry carries the path from `tools/` plus, separately, the name it gets
   in the block header. Deliberately different: the path changes when folders
   move, while the name is what you read in the deployed Worker. Using the path
   would make every move rewrite the whole `worker.js` and break byte-for-byte
   comparison between deploys. */
const FILES = [
  { paths: "../src/core.mjs", fileName: "core.mjs" },
  { paths: "../src/platforms/", fileName: "platforms", isDir: true },
  { paths: "../src/dispatch.mjs", fileName: "dispatch.mjs" },
  { paths: "../src/universal.mjs", fileName: "universal.mjs" },
  { paths: "../src/api.mjs", fileName: "api.mjs" },
  { paths: "../src/worker-entry.js", fileName: "worker-entry.js" },
];

/** Removes relative `import ... from "./x"` statements and `export` keywords. */
function strip(code) {
  return code
    // All three relative-import shapes: braces, single name, namespace.
    // Not anchored to line start on purpose: a comment can leave the `import`
    // glued to the `*/` above it.
    .replace(/import\s*\{[^}]*\}\s*from\s*"\.[^"]*"\s*;/g, "")
    .replace(/import\s+[A-Za-z_$][\w$]*\s+from\s*"\.[^"]*"\s*;/g, "")
    .replace(/import\s*\*\s*as\s+[\w$]+\s+from\s*"\.[^"]*"\s*;/g, "")
    // `export default` survives: the Worker needs that exact line, and it only
    // appears at the end of the file.
    .replace(/^export\s+(const|let|var|function|async function|class)\b/gm, "$1")
    .replace(/^export\s*\{[^}]*\};?[^\S\n]*$/gm, "")
    .trim();
}

/** Top-level names, so two definitions sharing a name get caught. */
function topLevelNames(code) {
  const found = [];

  for (const match of code.matchAll(/^(?:const|let|var|function|async function|class)\s+([A-Za-z_$][\w$]*)/gm)) {
    found.push(match[1]);
  }

  return found;
}

/**
 * Every file to flatten, in order, with the block header each gets.
 *
 * A directory is read and sorted, so `src/platforms/` turns into one entry per
 * platform without this file having to be edited when a platform is added. The
 * sort is on the name, so it does not depend on the filesystem's order — two
 * builds of the same tree produce the same bytes.
 */
async function sources() {
  const entries = [];

  for (const entry of FILES) {
    const url = new URL(entry.paths, import.meta.url);

    if (!entry.isDir) {
      entries.push({ paths: url, fileName: entry.fileName });
      continue;
    }

    const names = (await readdir(url)).filter((n) => n.endsWith(".js")).sort();

    if (!names.length) {
      throw new Error(`${entry.isDir} has no .js files in it: the Worker would have no extractors.`);
    }

    /* The trailing slash matters: `new URL("x.js", base)` resolves against the
       directory `base` points at, and a directory URL without one resolves
       against its parent. So without it every platform file was looked for in
       `src/` instead of `src/platforms/`. */
    for (const fileName of names) {
      entries.push({
        paths: new URL(`${fileName}`, url),
        fileName: `${entry.fileName}/${fileName}`,
      });
    }
  }

  return entries;
}

const parts = [];
const seen = new Map();

for (const { paths, fileName } of await sources()) {
  const code = strip(await readFile(paths, "utf8"));

  for (const name of topLevelNames(code)) {
    if (seen.has(name)) {
      throw new Error(
        `Collision: "${name}" is in ${seen.get(name)} and in ${fileName}. `
        + "Rename one of them before building the Worker.",
      );
    }

    seen.set(name, fileName);
  }

  parts.push(`/* ${"=".repeat(74)}\n   ${fileName}\n   ${"=".repeat(74)} */\n\n${code}`);
}

const banner = `/**
 * DOWNLOADER · Cloudflare Worker (single file)
 *
 * Generated by tools/build.mjs from src/core.mjs + src/platforms/ + src/dispatch.mjs
 * + src/universal.mjs + src/api.mjs + src/worker-entry.js.
 * Do not edit by hand: changes are lost on regeneration.
 *
 * Serves the API (/api/resolve, /api/media, /api/download) and the page at "/",
 * which is read from the repository and stored in Cloudflare's cache.
 *
 *   Deploy: paste this file into the Cloudflare dashboard, or
 *           npx wrangler deploy   (main = "worker.js")
 */

`;

/* The footer sits outside `FILES` on purpose: it is the only part not coming from
   a project source, so it gets its own block instead of hiding inside
   `worker-entry.js`. That way the pasted file shows at a glance that one line was
   added by the builder rather than written by hand.

   It runs when the isolate STARTS, not per request: in a module Worker the top
   level is evaluated once, when Cloudflare loads the file. Seeing it in the log
   means the whole module evaluated without throwing, which is the first thing to
   check when a deploy looks broken.

   No build date, deliberately. With one, two consecutive builds would differ even
   if no source changed, losing the byte-for-byte reproducibility that lets you
   diff one deploy against another. */
const footer = `/* ── startup ───────────────────────────────────────────────────────────── */
console.log("downloader · worker started");
`;

const output = banner + parts.join("\n\n") + "\n\n" + footer;

/* Better to fail here than to deploy a broken Worker and read the error in
   Cloudflare instead. */
for (const [pattern, why] of [
  [/from\s+"\./, "a relative import survived"],
  [/^import\b/m, "an import survived"],
  [/^export\s+(const|let|var|function|async function|class)\b/m, "an export declaration survived"],
  // A real `import`, not the word inside a comment.
  [/\bfrom\s*"node:/, "a node: import survived (Workers has none)"],
  // A dynamic `import("node:fs")` is not an import statement, so the two patterns
  // above never see it. In a Worker it is just as fatal: it throws on boot.
  [/import\s*\(\s*["']node:/, "a dynamic node: import survived (Workers has none)"],
]) {
  const match = output.match(pattern);

  if (match) {
    const line = output.slice(0, match.index).split("\n").length;

    throw new Error(`${why} on line ${line} of the output: ${match[0]}`);
  }
}

if (!/export\s+default\s*\{/.test(output)) {
  throw new Error("the output has no `export default`, which is what Cloudflare runs");
}

/* The backstop, and it is the one that matters.

   The five patterns above are all regexes over text, so they can only catch the
   malformation somebody thought of. This one asks the parser.

   The concrete hole it closes: `strip()` and the export check are both anchored
   with `^`, so an `export` that is not in column 0 survives both. An indented
   `export` is illegal in a module, so the *source* would not load either — and
   `tools/syntax.mjs` does catch it, but it runs after this file. Running this on
   its own, the build used to print "no collisions, no imports", write a
   `worker.js` that dies on boot with `Unexpected token '='`, and exit 0. The
   documented use of this file is "run the build, paste the result into the
   dashboard", so the last check before a deploy belongs here and not two steps
   later in a chain somebody may not run.

   `.mjs` because the output has a top-level `export default`, which is module
   syntax, and `node --check` on a `.js` would either retry it as CommonJS and
   complain about the export or, on Node 22, quietly accept things the Worker
   would not. */
const tempFile = new URL(`../.worker-check-${process.pid}.mjs`, import.meta.url);

try {
  await writeFile(tempFile, output, "utf8");
  execFileSync(process.execPath, ["--check", fileURLToPath(tempFile)], { stdio: "pipe" });
} catch (error) {
  const output = String(error.stderr ?? error.message ?? "");
  const line = /:(\d+)\n/.exec(output)?.[1];

  throw new Error(
    "the generated worker.js does not parse"
    + (line ? ` — line ${line} of the output` : "")
    + ".\nThat means the flattening produced something broken, and it is about to be"
    + " pasted into Cloudflare. Nothing was written.\n\n"
    + output.trim().split("\n").slice(0, 4).join("\n"),
  );
} finally {
  await rm(tempFile, { force: true });
}

await writeFile(new URL("../worker.js", import.meta.url), output);

const bytes = (await readFile(new URL("../worker.js", import.meta.url))).length;

console.log(`worker.js: ${bytes} bytes, ${seen.size} definitions, no collisions, no imports`);