import { dispatch, statusFor, json, setSecrets } from "./api.mjs";

/**
 * Cloudflare Worker. Serves the API and the page; nothing else.
 *
 * The page does not live inside the Worker: it is fetched from the repository
 * and stored in Cloudflare's cache, so the HTML is updated by pushing a commit
 * instead of requiring a deploy. When `worker.js` is generated by `build.mjs`,
 * this file is inlined into it and a single file is deployed.
 *
 * This is the only place that knows Cloudflare exists. `api.mjs` is plain
 * `fetch` and `Response`, which is why the Worker and the Node server share it
 * unchanged.
 */


/** Repository the page and the preview image come from. */
const REPO_RAW = "https://raw.githubusercontent.com/zendtay-studio/downloader/gh-pages";

const PAGE_URL = `${REPO_RAW}/index.html`;
const OG_IMAGE_URL = `${REPO_RAW}/images/og.png`;

/**
 * How long the page stays cached. The balance between not asking GitHub for the
 * HTML on every visit and seeing your own change soon: with an hour, at most one
 * visit per user reaches GitHub.
 */
const PAGE_MAX_AGE = 3600;

/**
 * The same policy, but in headers, for the browser. Without it GitHub sends its
 * own `cache-control`, which is aggressive and can serve a stale `index.html`
 * for days.
 */
const PAGE_HEADERS = {
  "Content-Type": "text/html; charset=utf-8",
  "Cache-Control": `public, max-age=${PAGE_MAX_AGE}`,
  "Content-Security-Policy": [
    "default-src 'self'",
    "img-src 'self' data: blob: https:",
    "media-src 'self' blob: https:",
    "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net",
    "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net",
    "connect-src 'self' https:",
    "font-src 'self' data:",
    "object-src 'none'",
    "base-uri 'none'",
    "form-action 'none'",
    "frame-ancestors 'none'",
  ].join("; "),
  "Referrer-Policy": "no-referrer",
  "X-Content-Type-Options": "nosniff",
};

const FALLBACK = "<!doctype html><meta charset=utf-8><title>Downloader</title>"
  + "<body style='font:16px system-ui;padding:2rem'>"
  + "<h1>The page could not be loaded</h1>"
  + "<p>It is normally read from the repository. Try again in a moment.</p>";

/**
 * These platforms will not accept a relative image: if the link is shared on
 * WhatsApp, Telegram or X, the tag is read from outside and with no host in front
 * there is nothing to download. It gets replaced here with the absolute URL of
 * the serving domain, which is why the HTML can be cached as-is without being
 * regenerated per domain.
 *
 * Only the page's own URL. The image no longer comes through here: all three
 * `og:image` and `twitter:image` tags carry the raw repository address in the
 * HTML, as requested. So it no longer depends on the serving domain — the same
 * works in production, on another domain and in the local copy — and a changed
 * image does not force a Worker redeploy.
 */
function absoluteUrls(html, host) {
  const base = `https://${host}`;

  return html.replaceAll('content="/"', `content="${base}/"`)
    .replaceAll('rel="canonical" href="/"', `rel="canonical" href="${base}/"`);
}

/**
 * The page, with Cloudflare's cache in front. If the cache is unavailable (local
 * environment, or a plan that disables it) it is still read from GitHub, just not
 * stored: serving the page does not depend on a cache existing.
 */
async function page(host) {
  const cache = globalThis.caches?.default ?? null;

  try {
    let html = null;

    if (cache) {
      const hit = await cache.match(PAGE_URL);

      if (hit) html = await hit.text();
    }

    if (html === null) {
      const response = await fetch(PAGE_URL, { headers: { "User-Agent": "downloader-worker" } });

      if (!response.ok) throw new Error(`GitHub responded ${response.status}`);

      html = await response.text();

      if (!html.includes("<html")) throw new Error("GitHub returned no HTML");

      // The HTML is stored as-is, before the URLs are touched, so the same copy
      // serves on any domain.
      if (cache) {
        await cache.put(PAGE_URL, new Response(html, { status: 200, headers: PAGE_HEADERS }));
      }
    }

    return new Response(absoluteUrls(html, host), { status: 200, headers: PAGE_HEADERS });
  } catch (error) {
    console.error("could not fetch the page:", error?.message ?? error);

    return new Response(FALLBACK, {
      status: 503,
      headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store" },
    });
  }
}

/** The preview image, with the same cache as the page. */
async function ogImage() {
  const cache = globalThis.caches?.default ?? null;

  try {
    if (cache) {
      const hit = await cache.match(OG_IMAGE_URL);

      if (hit) return hit;
    }

    const response = await fetch(OG_IMAGE_URL, { headers: { "User-Agent": "downloader-worker" } });

    if (!response.ok) throw new Error(`GitHub responded ${response.status}`);

    const ready = new Response(response.body, {
      status: 200,
      headers: {
        "Content-Type": "image/png",
        "Cache-Control": `public, max-age=${PAGE_MAX_AGE}`,
      },
    });

    if (cache) await cache.put(OG_IMAGE_URL, ready.clone());

    return ready;
  } catch (error) {
    console.error("could not fetch the image:", error?.message ?? error);

    /* 404 with a body, not an empty response: it is nearly always that the PNG
       has not been uploaded to the repository yet, and that is not guessable. */
    return new Response(
      JSON.stringify({
        error: "The preview image is not in the repository yet.",
        where: OG_IMAGE_URL,
        fix: "Upload images/og.png to the gh-pages branch: git add images/og.png && git commit -m \"og\" && git push",
      }),
      { status: 404, headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" } },
    );
  }
}

/* The installable app's manifest and its three icons.
 *
 * The Worker is what serves the site — the domain points here, not at GitHub
 * Pages — so every file the page asks for has to be a route in here. Without
 * these, the manifest and the icons fell through to the JSON 404 and the page
 * quietly stopped being installable: the manifest link resolved, the fetch came
 * back 404, and there is no error on screen to say so.
 *
 * Served from the repository the same way the preview image is, and with its own
 * Content-Type: the manifest is the one that matters, since a static host answers
 * `application/octet-stream` for an extension it does not know and Chrome fills
 * the console with a warning on every load.
 */
const APP_FILES = {
  "/site.webmanifest": ["application/manifest+json", "site.webmanifest"],
  "/images/icon-192.png": ["image/png", "images/icon-192.png"],
  "/images/icon-512.png": ["image/png", "images/icon-512.png"],
  "/images/icon-maskable.png": ["image/png", "images/icon-maskable.png"],
};

async function appFile(ruta) {
  const [tipo, archivo] = APP_FILES[ruta];
  const url = `${REPO_RAW}/${archivo}`;
  const cache = globalThis.caches?.default ?? null;

  try {
    if (cache) {
      const hit = await cache.match(url);

      if (hit) return hit;
    }

    const response = await fetch(url, { headers: { "User-Agent": "downloader-worker" } });

    if (!response.ok) throw new Error(`GitHub responded ${response.status}`);

    const ready = new Response(response.body, {
      status: 200,
      headers: {
        "Content-Type": tipo,
        "Cache-Control": `public, max-age=${PAGE_MAX_AGE}`,
      },
    });

    if (cache) await cache.put(url, ready.clone());

    return ready;
  } catch (error) {
    console.error(`could not fetch ${ruta}:`, error?.message ?? error);

    return new Response(
      JSON.stringify({
        error: `${archivo} is not in the repository yet.`,
        where: url,
        fix: `Upload images/${archivo} to the gh-pages branch and push.`,
      }),
      { status: 404, headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" } },
    );
  }
}

export default {
  async fetch(request, env) {
    /* First of all, before anything gets resolved: the secrets have to be in place
       by the time an extractor reaches the line that reads them. Without this
       the Worker boots fine, answers fine, and every valid cookie set in the
       dashboard is ignored without a word. */
    setSecrets(env);

    const url = new URL(request.url);

    if (request.method !== "GET" && request.method !== "HEAD") {
      return json({ error: "Method not allowed" }, 405);
    }

    try {
      if (url.pathname.startsWith("/api/")) {
        return await dispatch(request, url);
      }

      if (url.pathname === "/" || url.pathname === "/index.html") {
        return await page(url.host);
      }

      if (url.pathname === "/images/og.png" || url.pathname === "/og-image.png") {
        return await ogImage();
      }

      if (APP_FILES[url.pathname]) {
        return await appFile(url.pathname);
      }

      if (url.pathname === "/favicon.ico") return new Response(null, { status: 204 });

      return json({ error: "Not found" }, 404);
    } catch (error) {
      return json({ error: error.message || "Unexpected error" }, statusFor(error));
    }
  },
};